### ISSUE TITLE
Add new check-X commands to pylexibank

### ISSUE THREAD

**Issue by LinguList** [lexibank/pylexibank#113]
We discussed this just now (lexibankers in Jena), we would add the following commands (maybe more), with the namespace `check-*`:

* `check-languages`: tell which columns are in `cldf/languages.csv`, maybe check glottocodes, ettc.
* `check-concepts`: check basic statistics of the concepts, again the columns, but also mergers in concepticon, etc.
* `check-segments`: in fact, this is the `check_profile` command, which would be adjusted with namespace in the terminal
* `check-profile`: could be another command that actually checks, to which degree the orthography profile is suffering from duplicates, and how many statements are actually not needed for conversion

**Comment by SimonGreenhill** [comment]
We've got a [starting point here](https://github.com/lexibank/pylexibank/blob/master/src/pylexibank/commands/check.py)

**Comment by LinguList** [comment]
Yes, all check commands should be added there, in fact. I have mine in util.py so far.

**Comment by SimonGreenhill** [comment]
#109 might be a good check too.

**Comment by xrotwang** [comment]
With the new setup, based on `cldfbench`, a collection of checks could also go into a separate package - `lexicheck` maybe? - which would simply provide a couple of check commands, nicely namespaced via the entry point:
```bash
cldfbench lexicheck.concepts ...
```

**Comment by SimonGreenhill** [comment]
True, but these are probably very specific to lexibank and might not merit decoupling?

**Comment by SimonGreenhill** [comment]
Yes, just worried about how many moving parts we have. I don't want to have to remember which check lives in which package! Can we give `cldfbench` a set of default checks, and lexibank check runs those as well?

**Comment by xrotwang** [comment]
@SimonGreenhill yes, accidental complexity is a real issue here. And I have to admit that I do not yet see the ideal way to slice and dice and package functionality here.

I think we must have a clear understanding of what each layer adds:
- `csvw`: read and write CSV packages
- `pycldf`: basic functionality to read, write and validate CLDF - i.e. CSV packages + semantics
- `cldfbench`: an extensible cli + more assumptions regarding directory layout and curation workflows + (CLDF) dataset discovery
- `pylexibank`: assumes we are dealing with `Wordlist`s; thus adds tailored functionality for this case on top of `cldfbench`.

So, checks of the "language coordinates" kind should go into `cldfbench`, because they are not `Wordlist` specific. But the idea of separate checks-packages came up because
- `cldfbench` now provides a plugin architecture, which supports this
- separate packages allow development independent of the main package - which we may want to keep stable for reproducibilty reasons.

**Comment by SimonGreenhill** [comment]
Ok, let's back up. Why I keep on at this is because even though there's a small number of us working on lexibank, we're still not converging on a similar style, and it's pretty messy and variable at the moment. 

I keep thinking about how R handles package submission -- R CMD check for my `rcldf` package does this:

```shell
✔  checking for file ‘/Users/simon/projects/rcldf/DESCRIPTION’ ...
─  preparing ‘rcldf’:
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
✔  creating vignettes (2.2s)
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘rcldf_0.1.0.tar.gz’
   
── Checking ─────────────────────────────────────── rcldf ──
Setting env vars:
● _R_CHECK_CRAN_INCOMING_REMOTE_: FALSE
● _R_CHECK_CRAN_INCOMING_       : FALSE
● _R_CHECK_FORCE_SUGGESTS_      : FALSE
── R CMD check ─────────────────────────────────────────────────────────────────
─  using log directory ‘/Users/simon/projects/rcldf.Rcheck’
─  using R version 3.6.1 (2019-07-05)
─  using platform: x86_64-apple-darwin18.6.0 (64-bit)
─  using session charset: UTF-8
─  using options ‘--no-manual --as-cran’
✔  checking for file ‘rcldf/DESCRIPTION’ ...
─  checking extension type ... Package
─  this is package ‘rcldf’ version ‘0.1.0’
─  package encoding: UTF-8
✔  checking package namespace information
✔  checking package dependencies (3.5s)
✔  checking if this is a source package
✔  checking if there is a namespace
✔  checking for executable files (491ms)
✔  checking for hidden files and directories
✔  checking for portable file names ...
✔  checking for sufficient/correct file permissions
✔  checking serialization versions
✔  checking whether package ‘rcldf’ can be installed (1.4s)
✔  checking installed package size ...
✔  checking package directory ...
✔  checking for future file timestamps (845ms)
✔  checking ‘build’ directory
✔  checking DESCRIPTION meta-information ...
✔  checking top-level files
✔  checking for left-over files
✔  checking index information (352ms)
✔  checking package subdirectories (397ms)
✔  checking R files for non-ASCII characters ...
✔  checking R files for syntax errors ...
✔  checking whether the package can be loaded ...
✔  checking whether the package can be loaded with stated dependencies ...
✔  checking whether the package can be unloaded cleanly ...

(...you get the idea)   

 
── R CMD check results ──────────────────────────────────────── rcldf 0.1.0 ────
Duration: 19.7s

0 errors ✔ | 0 warnings ✔ | 0 notes ✔
```

... i.e. it checks lots of things from code validity to best practice stuff. I think this is a great way to offload complexity and standardise as many things as we can ("this lexibank dataset fails check X. Please fix!"). I'd recommend this as part of the dataset release process: step 1, make cldf, step 2, check, step 3 fix, step 4 release.

So, in this case, the question is whether `cldfbench` datasets should have specific assumptions about them i.e. a value defined as `Latitude` should be a float, a glottocode should be valid and non-bookkeeping. (Although perhaps there's  a case to be made for storing `Latitude` as "66° 34` N" in some cases?). Either way, I think that `lexibank` should use the checks valid for `cldfbench`, and extend them.

**Comment by SimonGreenhill** [comment]
So, I guess all this is an agreement that cldfbench should implement (a) a `check` command and (b) some basic checks (e.g. is a glottocode a string of 8 characters), while lexibank should extend these (e.g. is a glottocode a real non-bookmarking one?)

**Comment by LinguList** [comment]
I see it as follows:

1. keep the checks on the level where they belong (and this is probably straightforward)
2. inherit checks specific for a particular case if we think it's useful, so `lexicheck` or `lexibank.check_X` should offer the overarching check, similar to objects in OO programming

That means in fact just that we avoid a situation where we have to learn which package checks what, but can re-use that functionality in the lowest level we apply.

So I guess, we are on the same page (with previous posts).

**Comment by LinguList** [comment]
> while lexibank should extend these (e.g. is a glottocode a real non-bookmarking one?)

I'd say: cldfbench should do the same, as we'll need the coordinates as well, e.g., for structural data, and grambank.

A question not really solved: should we add coordinates from glottolog, or concepticon_gloss from concepticon, if only glottocode and concepticon_id are supplied? I'd opt to do so, for practiality reasons.

**Comment by SimonGreenhill** [comment]
Yes, I'd like a command like:

```shell
> lexibank check mydataset
Running checks
1. cldfbench.check_latitude .... passed!
2. cldfbench.check_valid_glottocode ... passed!
3. lexibank.check_valid_glottocode ... fail!
    - xxxx1234 is not a real glottocode!
```

... then you can rerun 

> lexibank check mydataset lexibank.check_valid_glottocode
... until you pass :)

**Comment by LinguList** [comment]
It will get complicated. But I think we see now much better how to think it through, so we can find a way to keep part of the complexity out of non-core lexibankers.

**Comment by SimonGreenhill** [comment]
Ok, I'd like to start working on this -- shall we create a new package called `lexicheck`?

**Comment by SimonGreenhill** [comment]
Moving discussion here: https://github.com/SimonGreenhill/lexicheck/
