### ISSUE TITLE
Column names

### ISSUE THREAD

**Issue by xrotwang** [lexibank/pylexibank#13]
While the CLDF we currently create with pylexibank is perfectly valid CLDF 1.0, it doesn't always use the default column names. This could be argued as an advantage, because it may better drive home the point that CLDF aware tools must judge a column by propertyUrl not name. But it also makes life for non-CLDF aware tools somewhat harder.

Currently these column names are also used as names of the corresponding SQLite db columns - and switching these to propertyUrls may be somewhat bulky. As additional complexity - in particular for querying the db, we have [one column name - `Index`](https://github.com/lexibank/pylexibank/blob/d5832c8d9831a7b8ca44567b618abfba22fdd272/src/pylexibank/cldf-metadata.json#L177-L180) which is ań SQL keyword, thus always has to be quoted.

So all the above is only meant as context for the question: Should we change the column names to the CLDF default names or not?

**Comment by xrotwang** [comment]
ping @SimonGreenhill @tresoldi @LinguList @chrzyki

**Comment by xrotwang** [comment]
Oh, btw. my vote goes to changing. If the result of the CLDF initiative is people standardizing on the default column names - and ignoring the propertyUrls - that would already be a change for the better. (It could be argued that the only purpose of the propertyUrls is distracting people and keeping them from discussing column naming ...)

**Comment by tresoldi** [comment]
In terms of lexibank, I think we should change. While CLDF must be open to the various needs people (might) have, the projects closely linked with CLDF should be as consistent (i.e., standardized) as possible, also in order to encourage this as a good practice (and it is probably make it easier for us in the long run).

Or maybe I'm just trying to fit [Postel's law](https://en.wikipedia.org/wiki/Robustness_principle) on being conservative in what we do and liberal in what we accept...

**Comment by SimonGreenhill** [comment]
Consistency is good. Reduces overheads and brain costs. Let's standardise now rather than wish we had in a years' time.

**Comment by chrzyki** [comment]
Either I'm too slow today or DLCE's moving to fast; anyway, just for completion's sake: my vote goes very strongly in favour of changing.
