### ISSUE TITLE
formspec replacements

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#142]
I'm liking the formspec way of handling form cleaning, but notice that a lot of datasets do manual stripping/replacing of characters e.g. robinsonap has a proto-language where all forms have a leading `*` to indicate they're reconstructions.  It's easy to do this with string replace, but its not clear when to do this (before or after formspec?).

Is it worth adding an extra argument to formspec of `replacements` e.g. 

```python
    form_spec = FormSpec(
        brackets={"[": "]", "{": "}", "(": ")"},
        separators=";/,",
        missing_data=('?', '-', '', ''),
        replacements = {
            "*": "",   # remove *
            "ts": "ʦ",   # replace characters with digraph
        },
        strip_inside_brackets=True
    )
````

The default would be `{}`, but this could be easily overridden in datasets and means our replacement code would then be consistent too.

**Comment by tresoldi** [comment]
Yes! I am working on `satterwhitetb` an was just about to suggest the same thing.

Depending on the raw data, there are cases where we simplest and easier solution is to perform replacements. Better to have them in an official way.

Just one thing: should they be passed as a dictionary, as you suggest? Even though Python from 3.6 keeps the dictionary order (but I think it is only guaranteed from 3.7 on), I would prefer to have a list of lists/tuple/dictionaries, so that we know and define the order of replacements. I would not like to run into complex bugs where the order of the replacements is the issue.

**Comment by LinguList** [comment]
Yes, I agree, as I also use these at times, and even for segmented data, I have ugly dictionaries from which I pull them.

But note that, since these replacements, of which we assume that they are simple `x.replace(a, b)` python statements, no regexes, might also be transparently put into a file.

Note also that the asterisk is something that should be deleted by the orthoprofile. 

So the question is: to which degree will we need replacements (I think: yes, they are useful, they could be offered by the formspec or used by it), and where do we want to place them? 

I would advocate to have a list of `etc/replacements.tsv` with those replacements listed.

**Comment by LinguList** [comment]
@tresoldi, `satterthwaitetb` does not need replacements, as it does not have real forms that could be segmented, so I'd say: don't invest too much time, just add the value from froms, maybe just using the `FirstFormOnlyFormSpec` or how it is called.

**Comment by tresoldi** [comment]
@LinguList there minor things: for example brackets/parentheses are stripped along with their contents, but three graphemes (y/r/ɨ) are preserved. This is currently done by replacing `(y)` with `y` and so on, before bracket stripping. I would suggest this is a case for regular expressions (`"\(([yrɨ])\)"` to `"\1"`), but don't worry, I'm happy with three manual replacements. :wink:

**Comment by LinguList** [comment]
But you have a default keyword saying you should not strip inside brackets, right? I'd say, that these things should only be done if there's no other workaround. Otherwise, it's a case for lexemes.tsv, if there are some 20 cases only.

**Comment by tresoldi** [comment]
Yes, but some of the material needs to be stripped, such as numbers (e.g., `(1)`), question marks (`?`), and so on. We could have a list of material to be preserved, but it sound too complex -- better to just run three replacements, in my opinion.

**Comment by LinguList** [comment]
Important, just discussing with @chrzyki a similar problem, in `diacl`. I think, for now, it is enough to write ONE derivate of a FormSpec, that accepts a list of replacments, and I volunteer to propose this, together with @chrzyki, and we will share here soon. 

THEN: I would ask both you @SimonGreenhill and you @tresoldi, to use this as well, and next week, we discuss with @xrotwang if we want to add this `FormSpecWithReplacement`.

So give us 5-10 minutes...

**Comment by LinguList** [comment]
```python
from pylexibank import FormSpec
import attr

@attr.s
class FormSpecWithReplacement(FormSpec):
    replacements = attr.ib(
        default={}, 
        validator=attr.validators.instance_of(dict)

    def clean(self, form, item=None):
        # make replacements first
        for s, t in sorted(self.replacements.items(), key=lambda x: len(x[0]), reverse=True):
            form = form.replace(s, t)
        if form not in self.missing_data:
            if self.strip_inside_brackets:
                return text.strip_brackets(form, brackets=self.brackets)
            return form
```

**Comment by LinguList** [comment]
@SimonGreenhill, @chrzyki, @tresoldi, let's try this with our respective datasets, and then maybe add it to pylexibank, if it satisfies everybody?

**Comment by SimonGreenhill** [comment]
Looks good, but I don't know if we need a subclass, rather then just a default empty arg in FormSpec (simpler is better! :)

It looks like the * is in the orthoprofile for robinsonap anyway (=NULL) so I'll see if that handles it too.

**Comment by LinguList** [comment]
I agree with simplicity, we also discussed with @chrzyki that we could just get rid of FirstFormOnlySpec by adding a flag: first_form = True/False as attribute. 

I suppose anyway to first go with this in case of @tresoldi and @chrzyki while your case @SimonGreenhill seems to be perfectly doable with orthoprofiles only.

**Comment by SimonGreenhill** [comment]
Sounds good!

**Comment by chrzyki** [comment]
See here https://github.com/lexibank/diacl/issues/9 (still working on the code, please only check the forms for now if you want to have a look).

**Comment by tresoldi** [comment]
Looks very doable. I am commenting the boring and opaque data manipulation of `satterwhitetb` first (it is something to be discussed in the PR, I should be able to finish today), I'll try the new form spec later.

**Comment by tresoldi** [comment]
@LinguList I don't think we should sort the list of replacements. This case is not necessarily analogous to an orthographic profile, where we need to make sure to match the longest first. I'd prefer to apply them in the order provided by the user -- if there are side-effects due to the order, it is the user's responsibility to provide the list of replacements in an appropriate order.

**Comment by LinguList** [comment]
@tresoldi, I discussed this with @chrzyki and it is obviously clear that the most consistent way of replacement is longest first, or do you have immediate cases where longest first yields bad results? The alternative of user-input would require to change the spec by using a list of tuples `[('t', 'k'), ('th', 's')]` with source and target. I am also fine with that. Only the validataor has to be changed then, and the default would be: `(,)` or `[]`

**Comment by tresoldi** [comment]
@LinguList I am not entirely sure it is obvious, because the case for replacements is when stuff cannot be solved in a "proper" way and, during debugging, we need to manually add some corrections. It could happen that a replacement added at a later stage invalidates a previous one, just because it happens to be a substring of it.

But I can live with it, no real feelings about it. Given that it is a dictionary and not a list, I would even expected the order not to be preserved. Let's just cache the sorted replacements when implementing.

**Comment by chrzyki** [comment]
Okay! Sounds good. Thanks for the feedback as well @tresoldi.

**Comment by chrzyki** [comment]
Yeah, sorry, force of habit with the OrderedDicts. :)

```python
if self.replacements:
    for rep in self.replacements:
        form = form.replace(rep[0], rep[1])
```
