### ISSUE TITLE
formspec replacing multiple spaces

### ISSUE THREAD

**Issue by tresoldi** [lexibank/pylexibank#146]
Should we have boolean flag, defaulting to `False`, to consume multiple spaces into a single one? In short, applying `re.sub("\s+", " ", form)`.

There is no real way of doing this with pure string replacements, unless we know in advance the length of the longest sequence of space characters.

**Comment by xrotwang** [comment]
Seems useful. Maybe this should be rolled into a normalization function together with unicode normalization?

**Comment by SimonGreenhill** [comment]
+1 on that

**Comment by LinguList** [comment]
Yes. I'd also suggest that we add the replacement issue questions in there, and I advocate for a single formspec, without inheritance, where the FirstFormOnlySpec is addressed by a boolean flag. (see our discussion here: #142).

**Comment by tresoldi** [comment]
Agreed, and `.strip()` and the end does not hurt.

**Comment by xrotwang** [comment]
Are there valid use cases for preserving multi-spaces - other than maybe a principle like "it must be possible to express identity as FormSpec"?

**Comment by SimonGreenhill** [comment]
If I say no, I'm sure the next dataset I come across will use meaningful whitespace in some way 🤷,  but I can't see any reason not to cull these.

**Comment by xrotwang** [comment]
Ok, just occurred to me that we may run into data where an editor may have turned tabs into multiple spaces - which cannot be used as `separators`, because this would be more than one character long.
Anyway, having this configurable won't hurt.

But I guess **one** flag for **all** whitespace normalization (stripping and collapsing) is sufficient - i.e. when whitespace **is** significant, it may also be significant at start and end?

**Comment by SimonGreenhill** [comment]
Sounds good!

**Comment by xrotwang** [comment]
See #148
