### ISSUE TITLE
Issue warnings if unused entries in lexemes.csv

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#154]
I'm a little worried that some of the special case handling in lexemes.csv e.g https://github.com/lexibank/robinsonap/blob/master/etc/lexemes.csv is unclear.

It would be helpful to have a command to check all items in lexemes.csv are applied. Or show a warning during makecldf if a row is not used.

**Comment by LinguList** [comment]
I'd say, the check command could also be applied to the full form spec. Similar to the orthprofile command. The good thing is, you first run makecldf, then you run `cldfbench lexibank.check_profile dataset`, and it does not change anything, but will tell you if your profile is fixed. 

You could do the something similar for the value -> form conversion. And with the formspec, this is probably easy to apply, along the lines of the `check_profile` command. And it is fast. The problem is: if you convert `value` to `form`, there's no realy way to check, and you have 1-n output. So it is not necessarily trivial to see how a good command for checking would look like here, but what one COULD do is checking from value -> form -> tokens. Or outputting cases where formspec actually converts the value, and where it stays the same.

**Comment by SimonGreenhill** [comment]
An alternative would be to track these in makecldf and raise a warning if any of the rows are not used.

**Comment by SimonGreenhill** [comment]
@xrotwang is there an easy way to check for this in the new `check_x` functionality? Is it a matter of iterating over forms.csv and checking "Value" is in lexemes.csv?

**Comment by xrotwang** [comment]
@SimonGreenhill yes, I would think so:
```python
assert set(l['replacement'] for l in self.lexemes).issubset(f['Value'] for f in cldf['FormTable'])
```

**Comment by xrotwang** [comment]
Wait, I'm not completely sure we store the replacement from `lexemes.csv` in `FormTable` `Value`. Arguably, storing the source and submitting the replacement to the form cleaning machinery would make more sense.

**Comment by SimonGreenhill** [comment]
Looks like it works -- see PR https://github.com/lexibank/pylexibank/pull/178

**Comment by SimonGreenhill** [comment]
fixed here: https://github.com/lexibank/pylexibank/commit/ee4f43387a61be6e3f48bf4684a2f629aca60cb3
