### ISSUE TITLE
Enforce standardisation of column names

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#19]
Pylexibank should enforce standardisation of column names. We currently have both (Concepticon_ID, Concepticon_Gloss) and (conceptset, concepticon_gloss) used in datasets e.g.

https://github.com/lexibank/robinsonap/blob/master/cldf/parameters.csv
https://github.com/lexibank/kitchensemitic/blob/master/cldf/parameters.csv

We should standardise to maximise cross-dataset compatibility (and there may be other examples).

**Comment by xrotwang** [comment]
Hm. I guess consolidation of the files in `etc/` would be good. Right now they are treated very differently: `concepts.csv` doesn't get any treatment other than reading in its rows as `dict`s. In `languages.csv` we validate a `GLOTTOCODE` column, etc.

The best way forward would probably be to model these files as closely as possible after their counterparts in the CLDF spec.

**Comment by LinguList** [comment]
Yes, I agree, this was also confusing me for quite some time now. Similar, btw, with language names.

**Comment by LinguList** [comment]
If we standardize, we could also avoid nullage statements for adding concepts, like:

```
        wl = lingpy.Wordlist(self.raw.posix('arawakan_swadesh_100_edictor.tsv'))
        with self.cldf as ds:
            ds.add_sources(*self.raw.read_bib())
            for l in self.languages:
                ds.add_language(
                    ID=slug(l['Name']),
                    Name=l['Name'],
                    Glottocode=l['Glottocode']
                    )
            for c in self.concepts:
                ds.add_concept(
                    ID=slug(c['ENGLISH']),
                    Name=c['ENGLISH'],
                    Concepticon_ID=c['CONCEPTICON_ID'],
                    Portuguese_Gloss=c['PORTUGUESE']
                    )
```

This could probably all be easily just done within one function, I'm always repeating it. And if we add a slugged ID to the concepts ourselves, it's even easier to do it...

**Comment by LinguList** [comment]
I mean, imagine the same call signature:

```python

ds.add_languages(ID="Name", Name="Name", Glottocode="Glottocode")
```

**Comment by LinguList** [comment]
And with some extra code, we could even make slugging default:

```python
ds.add_concept(ID="ENGLISH", Name="ENGLISH", Concepticon_ID="CONCEPTICON_ID", id_transform=slug)
```

**Comment by xrotwang** [comment]
I'm about to roll this into a bigger PR, but I have one more question: I think the column names in `concepts.csv` and `languages.csv` should be exactly the ones required in the corresponding CLDF data files. If this is the case, there could be a shortcut method `add_concepts()` which just calls `add_concept(**d)` for each item in `Dataset.concepts`. I wouldn't allow any flexibility or convenience here, so when slugs as ID are needed, they'd need to be present in `concepts.csv` already. Otherwise we lose transparency and might just as well have the dataset pull fully custom data from somewhere else.

Now if we do this, wouldn't it make more sense to also rename `concepts.csv` to `parameters.csv`? Then - if these files are present in `etc/`, they would basically be copied to `cldf/` (except for some data enrichment from Concepticon and Glottolog)?

**Comment by LinguList** [comment]
I agree with this completely: the slugging, etc., was usually a nuisance also when preparing data files.

I'm not against renaming to parameters.csv, but I wonder what happens with Concepticon concept lists: can we add a similar routine that would -- if lists are identical -- allow us to draw from there? But than we would have a different namespace.

Furthermore: do we still need to define custom columns if our parameters.csv contains more data? E.g., concept in another language, etc.?

**Comment by xrotwang** [comment]
Concepticon concept lists are the preferred way to provide concept info, so yes, they should be easy to import as well. In fact, most of this naming confusion comes from the attempt to model `concepts.csv` after concept lists, with the idea that at the end of massaging a dataset into CLDF we'd have a concept list in `concepts.csv` ready to submit to Concepticon.

And now that I think of it again, this may actually be the better motivation. So maybe, if we make this explicit and well-documented, the differing column names will make sense after all?

Overall, the config data in `etc/` would still be somewhat confusing - but at least I'd see good reasons for it being the way it is:

- `languages.csv`: should be pretty much ready to be copied into `cldf/`, i.e. have columns as expected by CLDF
- `concepts.csv`: should look like a Concepticon concept list (except for it using local IDs, not the ones to be added by Concepticon)
- `lexemes.csv`: This is a special case anyway, simply replacing "bad" lexemes. So I think the column names here are fine.

**Comment by LinguList** [comment]
I'd prefer that!

One problem with submitting to concepticon is the multi-step workflow for submitting a concept list: description in `concepticon.tsv`, adding bibliography, etc. And it's a hen-egg problem as well now: if you submit a paper with the data in `concepts.csv`, the paper would be quoted later when it appears, but concepticon should already have it before the paper appears. This often means at least two releases: one where a dataset is released, and then a second one, when the data is released to concepticon. Or can we circumvent this by describing some preferred workflow? E.g., the paper with Abbie, on Dogon languages. Should we already prepare to submit a list to concepticon now?

**Comment by xrotwang** [comment]
I think the Concepticon policy of only adding lists which have a corresponding publication is good and should take preference. Having multiple releases of a dataset may well be seen as a feature rather than a bug, in particular, if we go with some sort of semantic versioning. So here's the workflow I see:

- work on dataset, which implies fleshing out `concepts.csv` until data (and paper) is ready (btw.: I think the corresponding publication for a concept list can also "just" be the published dataset).
- publish paper/dataset
- submit concept list to Concepticon
- publish new release of Concepticon, including the concept list
- update (and release) dataset, adding the reference to the concept list

Note that in terms of the CLDF, only metadata will change (assuming the concepticon mappings haven't changed). So for "one-off" datasets, which won't be curated over a longer time, this isn't much of change.

**Comment by xrotwang** [comment]
ok, so here's my proposal: https://github.com/lexibank/lexibank/blob/master/README.md#etc
Hopefully, with this bit of documentation most questions regarding stuff in `etc/` are answered.

What do you think @SimonGreenhill  @LinguList @tresoldi @chrzyki ?

**Comment by xrotwang** [comment]
Haha. I wasn't sure. And there is no "Concepticon spec" :)

**Comment by xrotwang** [comment]
Using [the code](https://github.com/clld/concepticon-data/blob/f00c6a32857b42557be5fa98a3fc9ff0a745b296/pyconcepticon/api.py#L171) as spec, I'd say we prefer `GLOSS`. So I wouldn't even mention `ENGLISH`.

**Comment by LinguList** [comment]
Ah: and if the conceptlist contains more information, like columns that are more or less standardized in concepticon (languages, for example), this could just retrieve info from concepticon for CLDF creation of parameters.csv and metadata.json, right?

**Comment by xrotwang** [comment]
Wait, `concepts.csv` is for cases where there is no associated concept list - so no additional columns can be retrieved. **But** `cocepts.csv` can still contain additional columns, which would need to be declared via additional attributes of custom subclass of [`Concept`](https://github.com/lexibank/pylexibank/blob/fa42fcf859c91b18f6f12c15d1a9869cc7ad2704/src/pylexibank/dataset.py#L65). Then, they'd go into `cldf/parameters.csv`.
