### ISSUE TITLE
default `id_factory` for add_concepts

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#201]
We've standardised the lexibank concept IDs, so most datasets do this:

```python
        concepts = args.writer.add_concepts(
            id_factory=lambda c: c.id.split('-')[-1]+ '_' + slug(c.english),
            lookup_factory="Name"
        )
```

It would be nice if we could just make that the default for `id_factory` so this works:

```python
    concepts = args.writer.add_concepts(lookup_factory="Name")
```
...and would mean we don't need to import clldutils.slug in each lexibank dataset. 

We could  also make "Name" the default lookup_factory as we're relying heaving on concepticon here so both the above `id_factory` and `lookup_factory` should be sensible defaults.

**Comment by xrotwang** [comment]
Changing an argument default is always non-backwards compatible, so I'd be a bit hesitant here. We also decided that using `slug` is potentially intransparent and should only be used explicitly, i.e. in the top-level code. So if anything, I'd rather go for `id_factory=lambda c: c.id` as default - but that's short enough to be repeated for each dataset?

**Comment by SimonGreenhill** [comment]
True, but I don't think we have any datasets just calling plain `add_concepts` without an explicit id_factory (I've grepped all the datasets I've currently got cloned) so it shouldn't break anything (and now's the time to break stuff right? :).

**Comment by xrotwang** [comment]
Ok, but I still vote for `id_factory=lambda c: c.id` - which basically turns the IDs into foreign keys into concepticon concepts and thus, improves transparence.

**Comment by LinguList** [comment]
What is important with respect to IDs is that they keep a slugged version of the english gloss, as this turned out to be essential for debugging in the past. Same for languages, by the way.

**Comment by xrotwang** [comment]
I can see this being nice or simpler for debugging, but I wouldn't say it's essential - the non-slugged english gloss is always just "one join away", right? Mabye better support for this in error messages or other debugging tools would be a better solution than baking semantics into IDs.

**Comment by LinguList** [comment]
The problem were cases where numbers were completely swapped, since a concept lists with IDS was takeing from another dataset. This is an issue that is devastating. It is of course possible to make the join and debug, but given the multiple problems we already have in creating a dataset, which costs quite some experience, and where we have all different levels of expertise, also in catching orthoprofile errors, etc., I think this little convenience of allowing one to simply look at "forms.csv" instead of having to do some extra coding (since one wants to browse through a file with a text editor), this convenience is something that I think will contribute a lot to data quality and also to data review on github.

**Comment by xrotwang** [comment]
Ok, but then I'd say the price for this convenience - and a transparent way to make user aware of this convenience - is the explicit passing of `id_factory`. The `id_factory` machinery is somewhat complex as is, so I wouldn't want to obscure it even more by adding a complex default, including the slightly opaque `slug`.

**Comment by LinguList** [comment]
I guess, we agree that we don't need this for the formal integrity, but rather as some kind of "best practice style", similar to not adding and address in a bibliography if one has the publisher. I am all for an explicit passing of id_factory. 

The larger issue is that we have a namespace change from concepticon proper to cldf (ENGLISH becomes Name, CHINESE doesn't have a counterpart, so I use "Chinese_gloss" now). I am also fine with that, and I think it may go too far to define everything here and would require a discussion of all things we might want to put into parameters.csv. 

If we want to discuss this, we would

- still need the possibility to add custom aspects deemed important for a given dataset, and
- have a richer set of variables one may want to pass.

In fact, one thing that may require a bit of fiddling is the fact that we have no easy way to get back from a given dataset in cldf/lexibank to the conceptlist in concepticon. By retaining the regular form of `ID.split('_')[0]+'_'+slug(concept['ENGLISH']`, one could identify the ID in concepticon, which may be important when additional data is submitted with the concept list that is lacking in the cldf dataset. One may even argue that it would not be needed to have any additional information on concepts, as long as the information can be found in the conceptlist in concepticon. But this requires some reflection, as it is tedious to import data when working on projects, like we do now, where data are aggregated and then converted to a new dataset. 

This aggregation aspect is something we need to think about on the long run as well. There are the simple computer-based approaches (simple in the sense of "aggregate everything and don't really look at it", as we do for clics), and there are the targeted studies on phylogenies and the like. Here, we need to find the right balance between what we put in CLDF already and what we ignore because we have the information save at some other place.

I find it difficult to make a clear decision here.

If, for example, we start using concepticon-conceptlist-ids consequently as parameter.id, we might want to add a convenience function to lexibank that aggregates the data into a spreadsheet so one can check it quickly by eyeballing the data after a dataset has been created. I could, I think, also live with that, but the drawback would be that during PRs this would be left to the one that makes the PR, and I could not tell if some big disturbance has been done to the data if they are submitted in a revised PR. 

Any ideas how to make sure that we can make a more convenient check during PRs, of the **actual data**? That is in fact the point that I consider as cumbersome. Maybe a markdown table showing a random selection of words (not random, maybe for each concept and each language one example)?

**Comment by xrotwang** [comment]
As long as lexibank releases (also of individual datasets) are based on **released versions** of the catalogs and curated via `cldfbench`, I don't see any problem with copying data from these catalogs (e.g. extended concept list data) into the lexibank dataset. The trade-off here is convenience vs. size, I think. And the size aspect probably only comes into play for aggregations like CLICS or "lexibank" - at which point excess data can be filtered out again.

So maybe we'd need a `pylexibank.Concept` subclass that defines its attributes by inspecting the JSON metadata that comes with a concept list?

**Comment by LinguList** [comment]
So I would argue for a slight amount of convenience, defined, e.g., by
the way I code also a lot of the private repos that are yet to be
published, for SEA languages.

For a subclass, this may indeed be interesting and useful, as for a
given area as SEA, for example, I have Chinese glosses almost per
default, and I could prepare a suggestion also for things that may
happen more often than one thinks when constructing the parameters.csv

**Comment by SimonGreenhill** [comment]
ok, i'm happy to leave `id_factory` alone (although I do want to make it easy to 'do the right thing' and agree with Mattis that meaningful primary keys are better than non-meaningful ones).

I think most of the discussion here is linked to [enhancing add_concepts](https://github.com/lexibank/pylexibank/issues/200) -- so perhaps that can move there, and we close this `id_factory` issue as `wontfix`?

**Comment by LinguList** [comment]
Yes! good idea!
