### ISSUE TITLE
post_process() hook for transparent CLDF schema modifications

### ISSUE THREAD

**Issue by chrzyki** [lexibank/pylexibank#206]
Occasionally, the CLDF schema needs to be modified after the CLDF creation with `makecldf` (e.g. to address warnings about empty tables etc.). Doing so explicitly in a `post_process()`-hook after the CLDF creation might be more transparent, easier to track and safer.

**Comment by xrotwang** [comment]
Just looked around how to implement this. It turns out that `cmd_makecldf` is called from **`cldfbench.Dataset._cmd_makecldf`**, **not** from `pylexibank`. But this hook would have to be called **after** `cmd_makecldf` and **before** `_cmd_makecldf` finishes (i.e. before things are written to disk). So I think we close this as too complicated/intrusive.
