### ISSUE TITLE
convert vs. install

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/pylexibank#23]
`convert` confuses me. I keep expecting `install`.  It's also not clear what's being converted -- the raw data to CLDF, the CLDF to database? Does it make sense to rename these to e.g. `makecldf` and `loaddb`?

**Comment by xrotwang** [comment]
`makecldf` seems most transparent, `loaddb` as well. I did away with `install` because that would have made documentation awkward, having to explain the difference between "pip install" and "lexibank install". Ideally, we'd also change the corresponding `Dataset` method names, although this will require changes in each dataset repos.

**Comment by SimonGreenhill** [comment]
actually `makedb` and `makecldf` is more consistent. 

What's the expected workflow? `download -> convert -> load -> analyze -> report`? 

Is `download -> makecldf -> makedb -> analyze -> report`  better?

**Comment by xrotwang** [comment]
`makedb` is somewhat orthogonal - while all the others change files in the dataset repository, `makedb` only affects the sqlite db. Since you'd ideally always want a consistent repos state, any of the other commands should trigger the remainder of the workflow - i.e. running `convert` should be followed by `analyze` and `report`. Maybe we can speed up the latter two, so that this becomes possible, and then we'd be down to `download` and `makecldf`.

**Comment by SimonGreenhill** [comment]
Yes, good idea. `analyze` is the time-consuming thing, report's just processing that json file. Although if it wasn't a separate step it could be given a JSON object directly (rather than round trip write JSON -> read JSON) which could help as the JSON files can be big.

**Comment by xrotwang** [comment]
Maybe analyze could be done right away, I.e when the segments are written
to CLDF. This could speed up the process, possibly significantly.

Simon J Greenhill <notifications@github.com> schrieb am Do., 10. Mai 2018,
11:10:

**Comment by LinguList** [comment]
Even more: we now check each token for consistency in analyze, if I recall properly! But with Ortho-Profiles, we don't need to do so: we can just go for the profile, check for CLTS/BIPA resolvability there, and then provide type-token frequencies. I guess, the whole analyze-code is probably in need of refactoring. But I'd have to find time to look back into the code. If clts is used upon each token, this is not economic and probably reason for speed problems.

**Comment by xrotwang** [comment]
True, we could also assemble token counters first and then run CLTS on the
keys of the resulting dict only. This should be straight forward.

Johann-Mattis List <notifications@github.com> schrieb am Do., 10. Mai 2018,
14:04:

**Comment by xrotwang** [comment]
I just ran a little experiment: Simply caching `BIPA` lookups (as well as soundclass translations) in `test_sequence` cuts down the `analyze` time for a large dataset like *northeuralex* from 58 secs to 22. Simply iterating over FormTable takes 12 secs - so if `analyze` would be done as part of `convert`, this would only add 10 secs. That sounds already good enough to merge `analyze` into `convert`, right?

**Comment by SimonGreenhill** [comment]
Sounds good to me.

**Comment by LinguList** [comment]
Yes, excellent!
