### ISSUE TITLE
Make IDs more stable/persistent/transparent

### ISSUE THREAD

**Issue by xrotwang** [lexibank/pylexibank#51]
Currently, form and cognate IDs are mostly created automatically, and simply sequentially. This means that any additional data (new concepts or new languages) has the potential to change IDs for **all** forms and cognates. This problem could be avoided mostly, by using automatic form IDs derived as `<Language_ID>-<Parameter-ID>-<sysnonym-count>`.

I think in most cases this would lead to stable IDs, and even in cases where this does not hold, the problem is somewhat contained: you could still screw up IDs for synonyms in one language, in case their order as returned by `split_forms` changes, but that's probably acceptable.

**Comment by xrotwang** [comment]
@SimonGreenhill @tresoldi @LinguList @chrzyki what do you think?

**Comment by LinguList** [comment]
I'm fine with this! I wonder how cognate ids could be handled. The problem is: it is not entirely clear whether they can be derived in general terms, as they can be global, involving abundant word forms, concepts, etc. On the other hand: we often derive them from the original dataset, so this does not show any particular problems. 

For automatic dolgopolsky-cognates, we could use the sound class as the value, as this IS the criterion for cognacy there, and the concept, if the ID is meant to be local.

**Comment by xrotwang** [comment]
Cognate IDs are - if assigned automatially - derived from the form ID (plus a sequential integer), which is ok, I guess. In the trivial cases (i.e. where each form is assigned to at most one cognate) this means they are as predictable as the form IDs.
