### ISSUE TITLE
orthograpy as dependency?

### ISSUE THREAD

**Issue by LinguList** [lexibank/pylexibank#65]
Maybe its too early for that, but the same way in which we have lists of concepts, we may want to have the orthography profile being reused or similar. For the time being, we could also resort to submitting all orthoprofiles created for lexibank data also to orthograpy, to see what we receive as critical mass?

**Comment by LinguList** [comment]
I also foresee the bad situation to require one profile per language, so multiple profiles, in some sense. Or one big profile, where each column gives language-specific conversions (if required so). I guess, by adding profiles to orthograpy we can already test a bit of seeing what information we want to store there as well.

E.g., to test a profile, one could/should, when submitting a profile to orthograpy, indicate:

* a lexibank dataset if there is
* a source
* a note
* a test list (?)
* a person who compiled it

I guess, we'll have to figure out with time, what is most useful here, but I kindof like the idea of a small test list, even if it cannot really be exhaustive.

**Comment by xrotwang** [comment]
I think this makes sense once we have
- CLDF 1.1 with CLTS support
- lexibank 1.0, which can provide a seed set of orthography profiles.

**Comment by xrotwang** [comment]
Note that we already support [multiple orthography profiles for a dataset which will be applied per `Language_ID`](https://github.com/lexibank/pylexibank/blob/14c4c3696866e55e8009e90c245c1a6bb13ec199/src/pylexibank/dataset.py#L154-L177). So maybe the way to specify profiles from `orthograpy` would be to re-use the `etc/orthography-profile` setup, but allow profiles to be links, i.e. just like Python's `*.egg-link`. So if the profile has a suffix `.link` rather than `.tsv`, we expect it to contain just the ID of a profile in `orthograpy`.

**Comment by tresoldi** [comment]
One issue I ran these days is that for some datasets (e.g., TNG) it would make more sense to have multiple orthography profiles applied per source, and not per language id. It would be of particular importance when lexemes for the same language variety come from different source (again, as in TNG).

**Comment by xrotwang** [comment]
@tresoldi That should already be possible, too. You'd need to pass a keyword `profile` into the `add_forms_*` call, selecting one of the filenames in `etc/orthography-profile`, see https://github.com/lexibank/pylexibank/blob/14c4c3696866e55e8009e90c245c1a6bb13ec199/src/pylexibank/dataset.py#L167-L169

**Comment by tresoldi** [comment]
@xrotwang I see! So we could just have files with the bibtex key. Nice.
